version: '3.3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: 'sqli'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  client:
    build: .
    restart: always
    ports:
      - '1337:1337'
    expose:
      - '1337'
    volumes:
      - ./ruby_client.rb:/app/ruby_client.rb
