version: '3.3'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql_server
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'anything123!'
    ports:
      - '1433:1433'
    expose:
      - '1433'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./entrypoint.sh:/entrypoint.sh
    command: ["/bin/bash", "-c", "/entrypoint.sh"]
  client:
    build: .
    container_name: mssql_client
    restart: always
    ports:
      - '1337:1337'
    expose:
      - '1337'
    volumes:
      - ./ruby_client.rb:/app/ruby_client.rb
